# Drupal with MYSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#

version: '3.3'

services:
  drupal:
    build:
      context: '.'
    environment:
      HOST: mysql
      DBASE: livingcol
      USER: 'admin'
      PASS: 'secret'
    ports:
      - 80:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ./sites:/var/www/html/sites
    restart: always

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: livingcol
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  drupal:
  db: